import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { useAuthContext } from "~/hooks/useAuthContext";
import NavBar from "~/components/Nav";
import UserProfile from "~/components/Profile/userProfile";
import Footer from "~/components/Footer";

const ProfilePage: NextPage = () => {
  const router = useRouter();
  const [userId, setUserId] = useState<string>();
  const { authState, authDispatch } = useAuthContext();
  const user = authState.user;

  useEffect(() => {
    const testUserId = router.query.userId;
    if (typeof testUserId === "string") {
      setUserId(testUserId);
    }
  }, [router.isReady, router.query.userId]);
  return (
    <>
      <Head>
        <title>Zyzan&apos;s Pizza</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center bg-zinc-50 dark:bg-zinc-800 dark:text-zinc-50 sm:bg-gradient-to-r sm:from-zinc-50 sm:via-amber-50 sm:to-zinc-50 dark:sm:bg-gradient-to-br dark:sm:from-zinc-700 dark:sm:to-zinc-800">
        <NavBar />
        {userId && <UserProfile userId={userId} />}
        <Footer />
      </main>
    </>
  );
};

export default ProfilePage;
