import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/Nav";
import PizzaMenu from "~/components/Menu/Pizzas";
import SpecialtyPizzasMenu from "~/components/Menu/SpecialtyPizzas";
import WingsMenu from "~/components/Menu/Wings";
import SidesMenu from "~/components/Menu/Sides";
import DessertsMenu from "~/components/Menu/Desserts";
import DrinksMenu from "~/components/Menu/Drinks";
import SaucesMenu from "~/components/Menu/Sauces";
import Footer from "~/components/Footer";

const Menu: NextPage = () => {
  return (
    <>
      <Head>
        <title>Zyzan&apos;s Pizza</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center bg-zinc-50 dark:bg-zinc-800 dark:text-zinc-50 sm:bg-gradient-to-r sm:from-zinc-50 sm:via-amber-50 sm:to-zinc-50 dark:sm:bg-gradient-to-br dark:sm:from-zinc-700 dark:sm:to-zinc-800">
        <NavBar />
        <PizzaMenu />
        <SpecialtyPizzasMenu />
        <WingsMenu />
        <SidesMenu />
        <DessertsMenu />
        <DrinksMenu />
        <SaucesMenu />
        <Footer />
      </main>
    </>
  );
};

export default Menu;
