import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/Nav";
import LogInForm from "~/components/SignIn/LogInForm";
import RegisterForm from "~/components/SignIn/RegisterForm";

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Zyzan&apos;s Pizza</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center bg-gradient-to-r from-zinc-50 via-amber-50 to-zinc-50 dark:bg-gradient-to-br dark:from-zinc-700 dark:to-zinc-800 dark:text-zinc-50">
        <NavBar />
        <div className="h-16">.</div>
        <div className="my-4 rounded-lg bg-gradient-to-b from-green-700 to-green-800 sm:max-w-screen-sm md:max-w-screen-md">
          <div className="grid grid-cols-2">
            <RegisterForm />
            <LogInForm />
          </div>
          <div className="h-0.5 bg-zinc-50"></div>
          <div className="m-2 flex justify-center">
            <button className="rounded-md border-2 border-zinc-50 p-1 text-2xl text-zinc-50 transition hover:bg-gradient-to-br hover:from-red-500 hover:to-red-600 hover:shadow-inner hover:shadow-red-600">
              Continue As Guest
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default SignIn;
