import { type NextPage } from "next";
import { useRouter } from "next/router";
import { useAuthContext } from "~/hooks/useAuthContext";
import Head from "next/head";
import NavBar from "~/components/Nav";
import SignInForm from "~/components/SignIn/SignIn";

const SignIn: NextPage = () => {
  const router = useRouter();
  const { authState } = useAuthContext();
  const { user } = authState;
  if (user) {
    void router.push(`/profile/${user.userId}`);
  }
  return (
    <>
      <Head>
        <title>Zyzan&apos;s Pizza</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark flex min-h-screen flex-col items-center bg-gradient-to-r from-zinc-50 via-amber-50 to-zinc-50 dark:bg-gradient-to-br dark:from-zinc-700 dark:to-zinc-800 dark:text-zinc-50">
        <NavBar />
        <div className="h-16"></div>
        <SignInForm />
      </main>
    </>
  );
};

export default SignIn;
