import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/Nav";

const Desserts: NextPage = () => {
  const ture = false;
  return (
    <>
      <Head>
        <title>Zyzan&apos;s Pizza</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-r from-zinc-50 via-amber-50 to-zinc-50 dark:bg-zinc-800">
        <NavBar />
        <div className="h-16">.</div>
      </main>
    </>
  );
};

export default Desserts;
